add_subdirectory(win32)
add_subdirectory(records)
add_subdirectory(work)
add_subdirectory(registry)
add_subdirectory(regfile)
add_subdirectory(search)
add_subdirectory(trace)
add_subdirectory(defaults)
add_subdirectory(changes)
add_subdirectory(workspace)
add_subdirectory(browse)
add_subdirectory(appearance)
add_subdirectory(editors)
add_subdirectory(cli)
add_subdirectory(frame)
